Vtope/Models/ErrorViewModel.cs
namespace Vtope.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vtope/Models/InstaAccount.cs
namespace Vtope.Models
{
    public class InstaAccount
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string? SessionData { get; set; }
        public bool IsUtil { get; set; }
    }
}

Vtope/Models/VtopeDbContext.cs
using Microsoft.EntityFrameworkCore;
using Vtope.Domain;

namespace Vtope.Models;

public class VtopeDbContext : DbContext
{
    public VtopeDbContext(DbContextOptions<VtopeDbContext> options) : base(options)
    {

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InstaAccount>().HasIndex(x => x.Username).IsUnique();
        modelBuilder.Entity<InstaAccount>().Property(x => x.Username).IsRequired().HasMaxLength(30);
        
        modelBuilder.Entity<InstaAccount>().Property(x => x.Password).IsRequired().HasMaxLength(30);
    }

    public DbSet<InstaAccount> InstaAccounts { get; set; }
}

Vtope/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Vtope.Models;

namespace Vtope.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vtope/Controllers/InstaAccountsController.cs
using Hangfire;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Vtope.Domain;
using Vtope.Models;
using Vtope.Service;

namespace Vtope.Controllers
{
    public class InstaAccountsController : Controller
    {
        private readonly VtopeDbContext _context;
        private readonly IInstaService _instaService;
        
        public InstaAccountsController(VtopeDbContext context, IInstaService instaService)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _instaService = instaService ?? throw new ArgumentNullException(nameof(instaService));
        }

        // GET: InstaAccounts
        public async Task<IActionResult> Index()
        {
              return _context.InstaAccounts != null ? 
                          View(await _context.InstaAccounts.ToListAsync()) :
                          Problem("Entity set 'VtopeDbContext.InstaAccounts'  is null.");
        }

        // GET: InstaAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.InstaAccounts == null)
            {
                return NotFound();
            }

            var instaAccount = await _context.InstaAccounts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (instaAccount == null)
            {
                return NotFound();
            }

            return View(instaAccount);
        }

        // GET: InstaAccounts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: InstaAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Password,SessionData,IsUtil")] InstaAccount instaAccount)
        {
            if (ModelState.IsValid)
            {
                _context.Add(instaAccount);
                await _context.SaveChangesAsync();
                
                //TODO change to domain event
                //var sessionData = await _instaService.Login(instaAccount.Username, instaAccount.Password);
                //if (!string.IsNullOrWhiteSpace(sessionData))
                //{
                //    instaAccount.SessionData = sessionData;
                //    await _context.SaveChangesAsync();
                //}

                ////TODO change to domain event
                //if (!instaAccount.IsUtil)
                //{
                //    BackgroundJob.Enqueue<IJobService>(x => x.PrepareAccount(instaAccount));

                //    var utilAccounts = await _context.InstaAccounts.Where(x => x.IsUtil).Take(15).AsNoTracking().ToListAsync();
                //    foreach (var utilAccount in utilAccounts)
                //    {
                //        BackgroundJob.Enqueue<IJobService>(x => x.FollowAccount(utilAccount.SessionData, instaAccount.Username));
                //    }
                //}

                return RedirectToAction(nameof(Index));
            }
            return View(instaAccount);
        }

        // GET: InstaAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.InstaAccounts == null)
            {
                return NotFound();
            }

            var instaAccount = await _context.InstaAccounts.FindAsync(id);
            if (instaAccount == null)
            {
                return NotFound();
            }
            return View(instaAccount);
        }

        // POST: InstaAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Password,SessionData,IsUtil")] InstaAccount instaAccount)
        {
            if (id != instaAccount.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(instaAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstaAccountExists(instaAccount.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(instaAccount);
        }

        // GET: InstaAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.InstaAccounts == null)
            {
                return NotFound();
            }

            var instaAccount = await _context.InstaAccounts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (instaAccount == null)
            {
                return NotFound();
            }

            return View(instaAccount);
        }

        // POST: InstaAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.InstaAccounts == null)
            {
                return Problem("Entity set 'VtopeDbContext.InstaAccounts'  is null.");
            }
            var instaAccount = await _context.InstaAccounts.FindAsync(id);
            if (instaAccount != null)
            {
                _context.InstaAccounts.Remove(instaAccount);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstaAccountExists(int id)
        {
          return (_context.InstaAccounts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Vtope/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Vtope/Views/InstaAccounts/Create.cshtml
@model Vtope.Domain.InstaAccount

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>InstaAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SessionData" class="control-label"></label>
                <input asp-for="SessionData" class="form-control" />
                <span asp-validation-for="SessionData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vtope/Views/InstaAccounts/Delete.cshtml
@model Vtope.Domain.InstaAccount

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InstaAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SessionData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SessionData)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Vtope/Views/InstaAccounts/Details.cshtml
@model Vtope.Domain.InstaAccount

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>InstaAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SessionData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SessionData)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Vtope/Views/InstaAccounts/Edit.cshtml
@model Vtope.Domain.InstaAccount

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>InstaAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SessionData" class="control-label"></label>
                <input asp-for="SessionData" class="form-control" />
                <span asp-validation-for="SessionData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vtope/Views/InstaAccounts/Index.cshtml
@model IEnumerable<Vtope.Domain.InstaAccount>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SessionData)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SessionData)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Vtope/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vtope</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vtope.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vtope</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InstaAccounts" asp-action="Index">Insta Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Vtope - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>